user_login:
    path:     /login
    defaults: { _controller: UserBundle:Authentication:login }
    methods:  ['GET']

user_register:
    path:     /register
    defaults: { _controller: UserBundle:Authentication:register }
    methods:  ['GET']

user_register_corporate:
    path:     /registerCorporate
    defaults: { _controller: UserBundle:Authentication:registerCorporate }
    methods:  ['GET']

user_register_driver:
    path:     /registerDriver
    defaults: { _controller: UserBundle:Authentication:registerDriver }
    methods:  ['GET']

user_register_hotel:
    path:     /registerHotel
    defaults: { _controller: UserBundle:Authentication:registerHotel }
    methods:  ['GET']

user_register_guide:
    path:     /registerGuide
    defaults: { _controller: UserBundle:Authentication:registerGuide }
    methods:  ['GET']

user_register_photographer:
    path:     /registerPhotographer
    defaults: { _controller: UserBundle:Authentication:registerPhotographer }
    methods:  ['GET']

user_hotel_page:
    path:     /hotelPage
    defaults: { _controller: UserBundle:Authentication:loadHotelPage }
    methods:  ['GET']

user_photographer_page:
    path:     /photographerPage
    defaults: { _controller: UserBundle:Authentication:loadPhotographerPage }
    methods:  ['GET']

user_guide_page:
    path:     /guidePage
    defaults: { _controller: UserBundle:Authentication:loadGuidePage }
    methods:  ['GET']

user_ride_page:
    path:     /ridePage
    defaults: { _controller: UserBundle:Authentication:loadRidePage }
    methods:  ['GET']

user_destination_page:
    path:     /destinationPage
    defaults: { _controller: UserBundle:Authentication:loadDestinationPage }
    methods:  ['GET']

user_add_new_destination:
    path:     /addNewDestination
    defaults: { _controller: UserBundle:Authentication:addNewDestination }
    methods:  ['GET']

user_add_new_contact:
    path:     /addNewContact
    defaults: { _controller: UserBundle:Authentication:addNewContact }
    methods:  ['GET']

user_load_police:
    path:     /loadPolice
    defaults: { _controller: UserBundle:Authentication:loadPolice }
    methods:  ['GET']

user_load_hospital:
    path:     /loadHospital
    defaults: { _controller: UserBundle:Authentication:loadHospital }
    methods:  ['GET']

user_load_Bank:
    path:     /loadBank
    defaults: { _controller: UserBundle:Authentication:loadBank }
    methods:  ['GET']

user_load_air_line:
    path:     /loadAirLine
    defaults: { _controller: UserBundle:Authentication:loadAirLine }
    methods:  ['GET']

user_traveler_data:
    path:     /travelerData
    defaults: { _controller: UserBundle:Authentication:travelerData }
    methods:  ['GET']

user_hotel_data:
    path:     /hotelData
    defaults: { _controller: UserBundle:Authentication:hotelData }
    methods:  ['GET']

user_guide_data:
    path:     /guideData
    defaults: { _controller: UserBundle:Authentication:guideData }
    methods:  ['GET']

user_photographer_data:
    path:     /photographerData
    defaults: { _controller: UserBundle:Authentication:photographerData }
    methods:  ['GET']

user_driver_data:
    path:     /driverData
    defaults: { _controller: UserBundle:Authentication:driverData }
    methods:  ['GET']

user_update_traveler:
    path:     /updateTraveler
    defaults: { _controller: UserBundle:Authentication:updateTraveler }
    methods:  ['GET']

user_make_payment:
    path:     /makePayment
    defaults: { _controller: UserBundle:Authentication:makePayment}
    methods:  ['GET']

user_get_messages:
    path:     /getMessages
    defaults: { _controller: UserBundle:Authentication:getMessages}
    methods:  ['GET']

user_get_corporate_account_name:
    path:     /getCorporateAccountName
    defaults: { _controller: UserBundle:Authentication:getCorporateAccountName}
    methods:  ['GET']











