user_login:
    path:     /login
    defaults: { _controller: UserBundle:Authentication:login }
    methods:  ['GET']

user_register:
    path:     /register
    defaults: { _controller: UserBundle:Authentication:register }
    methods:  ['GET']

user_register_corporate:
    path:     /registerCorporate
    defaults: { _controller: UserBundle:Authentication:registerCorporate }
    methods:  ['GET']

user_register_driver:
    path:     /registerDriver
    defaults: { _controller: UserBundle:Authentication:registerDriver }
    methods:  ['GET']

user_register_hotel:
    path:     /registerHotel
    defaults: { _controller: UserBundle:Authentication:registerHotel }
    methods:  ['GET']

user_hotel_page:
    path:     /hotelPage
    defaults: { _controller: UserBundle:Authentication:loadHotelPage }
    methods:  ['GET']